apiVersion: v1alpha1
kind: Setting
metadata:
  name: plugin-code-enhance-settings
spec:
  forms:
    - group: basic
      label: 基础设置
      formSchema:
        - $formkit: switch
          name: enableCodeFold
          label: 启用代码折叠
          value: true
          help: 超过指定行数的代码块将自动折叠
        - $formkit: number
          name: codeFoldLine
          label: 代码折叠行数阈值
          value: 20
          min: 1
          help: 超过此行数的代码块将自动折叠
        - $formkit: switch
          name: enableImgFold
          label: 启用长图折叠
          value: true
          help: 超过指定高度的图片将自动折叠
        - $formkit: number
          name: imgFoldHeight
          label: 图片折叠高度阈值（px）
          value: 400
          min: 1
          help: 超过此高度的图片将自动折叠
