apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  name: PluginCodeEnhance
spec:
  version: 2.0.1
  enabled: true
  requires: ">=2.20.0"
  author:
    name: "吴蛋蛋"
    website: https://wuqishi.com
  logo: static/images/dan.svg
  settingName: plugin-code-enhance-settings
  configMapName: plugin-code-enhance-configMap
  displayName: "代码折叠增强"
  description: "自动折叠长代码块和长图片，配置灵活"
  homepage: https://wuqishi.com
  repo: https://github.com/NoEggEgg/plugin-code-enhance
  license:
    - name: "GPL-3.0"
      url: "https://opensource.org/licenses/GPL-3.0"
